#!/bin/bash

echo "Checking ingestion spec file contents."

read -r -d '' VAR <<- EOM
{
    "type": "index_parallel",
    "spec": {
        "dataSchema": {
            "dataSource": "wikipedia",
            "timestampSpec": {
                "column": "time",
                "format": "auto"
            },
            "dimensionsSpec": {
                "dimensions": [
                    "user"
                ]
            },
            "metricsSpec": [
                {
                    "type": "count",
                    "name": "recordSum"
                },
                {
                    "fieldName": "added",
                    "name": "addedSum",
                    "type": "longSum"
                },
                {
                    "fieldName": "deleted",
                    "name": "deletedSum",
                    "type": "longSum"
                },
                {
                    "fieldName": "delta",
                    "name": "deltaSum",
                    "type": "longSum"
                }
            ],
            "granularitySpec": {
                "segmentGranularity": "day",
                "queryGranularity": "hour",
                "intervals": [
                    "2015-09-12/2015-09-13"
                ],
                "rollup": true
            }
        },
        "ioConfig": {
            "type": "index_parallel",
            "inputSource": {
                "type": "local",
                "baseDir": "/root/apache-druid-0.21.1/quickstart/tutorial/",
                "filter": "wikiticker-2015-09-12-sampled.json"
            },
            "inputFormat": {
                "type": "json"
            },
            "appendToExisting": false
        },
        "tuningConfig" : {
            "type" : "index_parallel",
            "maxRowsInMemory" : 25000,
            "maxBytesInMemory" : 250000,
            "partitionSpec" : {
              "type" : "dynamic",
              "maxRowsPerSegment" : 5000000
            }
        }
    }
}
EOM

if [ ! -s /root/ingestion-spec.json ]
then
  MSG="The ingestion spec is too small or does not exist - did you save the file in the editor?"
elif jq empty /root/ingestion-spec.json 2>/dev/null
 then
  DIFF=$(diff <( cat /root/ingestion-spec.json | jq ) <( echo "$VAR" | jq ))
  if [ "$DIFF" != "" ]
  then
    MSG='The ingestion spec is not quite correct (DID YOU SAVE THE FILE?) - '$(printf "%s" $DIFF)
  fi
else
  MSG="The ingestion spec JSON is not well formed (maybe check for missing commas or extra parens)"
fi


if [ ! -z "$MSG" ]
then
    fail-message "$MSG"
fi
