#!/bin/bash

#apt-get update
#apt-get install wget -y
#apt-get install -y libfindbin-libs-perl
#apt install openjdk-8-jre-headless -y
#apt install curl -y
#echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> /root/.bashrc
