#!/bin/bash

cat > /root/clickstream_dashboard.json <<-EOF
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 1,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "grafadruid-druid-datasource",
        "uid": "D-BD8_ZVk"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 123127,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "pluginVersion": "9.1.1",
      "targets": [
        {
          "builder": {
            "intervals": {
              "intervals": [
                "${__from:date:iso}/${__to:date:iso}"
              ],
              "type": "intervals"
            },
            "query": "SELECT time_floor(__time, 'PT1M') as \"time\", count(*) as \"Total changes\"\nFROM \"clickstream_data\"\nGROUP BY 1",
            "queryType": "sql"
          },
          "datasource": {
            "type": "grafadruid-druid-datasource",
            "uid": "D-BD8_ZVk"
          },
          "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT time_floor(__time, 'PT1M') as \\\"time\\\", count(*) as \\\"Total changes\\\"\\nFROM \\\"clickstream_data\\\"\\nGROUP BY 1\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}",
          "refId": "A",
          "settings": {}
        }
      ],
      "title": "Panel Title",
      "type": "timeseries"
    },
    {
      "datasource": {
        "type": "grafadruid-druid-datasource",
        "uid": "D-BD8_ZVk"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 8
      },
      "id": 123125,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "right",
          "showLegend": true
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "builder": {
            "intervals": {
              "intervals": [
                "${__from:date:iso}/${__to:date:iso}"
              ],
              "type": "intervals"
            },
            "query": "SELECT time_floor(__time, 'PT1M') as \"time\", client_country as \"metric\", count(*) \"country =\"\nFROM \"clickstream_data\"\nGROUP BY 1,2\n",
            "queryType": "sql"
          },
          "datasource": {
            "type": "grafadruid-druid-datasource",
            "uid": "D-BD8_ZVk"
          },
          "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT time_floor(__time, 'PT1M') as \\\"time\\\", client_country as \\\"metric\\\", count(*) \\\"country =\\\"\\nFROM \\\"clickstream_data\\\"\\nGROUP BY 1,2\\n\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{\"format\":\"wide\"}}",
          "refId": "A",
          "settings": {
            "format": "wide"
          }
        }
      ],
      "title": "Panel Title",
      "type": "timeseries"
    },
    {
      "datasource": {
        "type": "grafadruid-druid-datasource",
        "uid": "D-BD8_ZVk"
      },
      "gridPos": {
        "h": 3,
        "w": 24,
        "x": 0,
        "y": 16
      },
      "id": 1,
      "targets": [
        {
          "datasource": {
            "type": "grafadruid-druid-datasource",
            "uid": "D-BD8_ZVk"
          },
          "refId": "A"
        }
      ],
      "type": "welcome"
    },
    {
      "datasource": {
        "type": "grafadruid-druid-datasource",
        "uid": "D-BD8_ZVk"
      },
      "gridPos": {
        "h": 9,
        "w": 24,
        "x": 0,
        "y": 19
      },
      "id": 123123,
      "targets": [
        {
          "datasource": {
            "type": "grafadruid-druid-datasource",
            "uid": "D-BD8_ZVk"
          },
          "refId": "A"
        }
      ],
      "type": "gettingstarted"
    },
    {
      "datasource": {
        "type": "grafadruid-druid-datasource",
        "uid": "D-BD8_ZVk"
      },
      "gridPos": {
        "h": 15,
        "w": 12,
        "x": 0,
        "y": 28
      },
      "id": 3,
      "links": [],
      "options": {
        "folderId": 0,
        "maxItems": 30,
        "query": "",
        "showHeadings": true,
        "showRecentlyViewed": true,
        "showSearch": false,
        "showStarred": true,
        "tags": []
      },
      "pluginVersion": "9.1.1",
      "tags": [],
      "targets": [
        {
          "datasource": {
            "type": "grafadruid-druid-datasource",
            "uid": "D-BD8_ZVk"
          },
          "refId": "A"
        }
      ],
      "title": "Dashboards",
      "type": "dashlist"
    },
    {
      "datasource": {
        "type": "grafadruid-druid-datasource",
        "uid": "D-BD8_ZVk"
      },
      "gridPos": {
        "h": 15,
        "w": 12,
        "x": 12,
        "y": 28
      },
      "id": 4,
      "links": [],
      "options": {
        "feedUrl": "https://grafana.com/blog/news.xml",
        "showImage": true
      },
      "targets": [
        {
          "datasource": {
            "type": "grafadruid-druid-datasource",
            "uid": "D-BD8_ZVk"
          },
          "refId": "A"
        }
      ],
      "title": "Latest from the blog",
      "type": "news"
    }
  ],
  "schemaVersion": 37,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-15m",
    "to": "now"
  },
  "timepicker": {
    "hidden": true,
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ],
    "time_options": [
      "5m",
      "15m",
      "1h",
      "6h",
      "12h",
      "24h",
      "2d",
      "7d",
      "30d"
    ],
    "type": "timepicker"
  },
  "timezone": "browser",
  "title": "Clickstream Dashboard",
  "uid": "VfRe__W4z",
  "version": 3,
  "weekStart": ""
}
EOF
