#!/bin/bash


#apt-get install python3 -y
#apt install python3-pip -y
#pip install plotext
#pip3 install requests

# Install kafka
#curl -O https://archive.apache.org/dist/kafka/2.7.0/kafka_2.13-2.7.0.tgz
#tar -xzf kafka_2.13-2.7.0.tgz

DEBIAN_FRONTEND=noninteractive apt -y install screen

# Create the producer script
cat > /root/process-monitor-producer.sh << \EOF
# $1 is ISO or UNIX
# $2 is CSV or JSON
# $3 is the number of times to run top or 0 to run forever
if [[ $3 != "0" ]]
then
  N_OPTION=" -n $3 "
fi
if [[ $2 == "CSV" ]]
then
  printf "time,pid,processName,cpu,memory\n" $(date --utc +%FT%TZ) $pid $name $cpu $mem
fi
top -d 0.1 -b $N_OPTION | \
  grep -w -E "^\s*[0-9]+" | \
  awk '{print $1 " " $9 " " $10}' | \
  while read -r pid cpu mem
    do
      ps -ef | awk 'NF{print $2 " " $8}' | \
        while read -r pspid name
          do
            if [[ "$pid" == "$pspid" ]]
              then
                if [[ $1 == "ISO" ]]
                then
                  if [[ $2 == "CSV" ]]
                  then
                    printf "%s,%s,%s,%s,%s\n" $(date --iso-8601=ns | awk 'BEGIN { FS = ","} ; {printf "%s.%03d", $1, $2/1000000}') $pid $name $cpu $mem
                  else
                    printf "{\"__time\":\"%s\",\"pid\":\"%s\",\"processName\":\"%s\",\"cpu\":%s,\"memory\":%s}\n" $(date --iso-8601=ns | awk 'BEGIN { FS = ","} ; {printf "%s.%03d", $1, $2/1000000}') $pid $name $cpu $mem
                  fi
                else
                  if [[ $2 == "CSV" ]]
                  then
                    printf "%s,%s,%s,%s,%s\n" $(date +%s%N | cut -b1-13) $pid $name $cpu $mem
                  else
                    printf "{\"__time\":\"%s\",\"pid\":\"%s\",\"processName\":\"%s\",\"cpu\":%s,\"memory\":%s}\n" $(date +%s%N | cut -b1-13) $pid $name $cpu $mem
                  fi
                fi
              fi
          done
    done
EOF
chmod +x /root/process-monitor-producer.sh

cat > ~/.screenrc <<-EOF
# ~/.screenrc configuration file

# Set the default shell
shell "/bin/bash"

# These lines give us a pretty navigation bar at the bottom
hardstatus off
hardstatus alwayslastline
hardstatus string '%{= kW}[ %{m}%H %{W}][%= %{= kw}%?%-Lw%?%{r}(%{g}%n*%f%t%?(%u)%?%{r})%{w}%?%+Lw%?%?%= %{W}][%{Y} %d/%m %{Y}%c %{W}]'

# Disable the startup message
startup_message off

# Disable Visual Bell
vbell off

# Increase the scrollback buffer
defscrollback 5000

# Use SHIFT-right and SHIFT-left arrow to change windows
bindkey ^[[1;2D prev
bindkey ^[[1;2C next

# Add your own programs here to auto-start them in a window.
screen -t shell 0
EOF

# Append this onto the end of ~/.bashrc
# The \ ensures the target file has a literal $STY and not an empty string.
cat >> ~/.bashrc <<-EOF
if [[ -z "\$STY" ]]; then
   screen -xRR default
fi
EOF
